# Generated by Django 4.0 on 2022-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0002_alter_about_options_alter_about_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
