# Generated by Django 4.0 on 2022-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0003_about_about_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_photo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'about url',
            },
        ),
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'about',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
