# Generated by Django 4.0 on 2022-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0004_aboutphoto_abouttext_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trips_photo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trips Page Photo URLs',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutphoto',
            options={'verbose_name_plural': 'About Photo URL'},
        ),
        migrations.AlterModelOptions(
            name='abouttext',
            options={'verbose_name_plural': 'About Text'},
        ),
    ]
