# Generated by Django 4.0 on 2022-03-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0005_tripsphotos_alter_aboutphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsphotos',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
