# Generated by Django 4.0.2 on 2022-05-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0008_detroit2020photos_la2021photos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denver2020photos',
            options={'verbose_name_plural': 'Denver 2020 Photos'},
        ),
        migrations.AlterModelOptions(
            name='detroit2020photos',
            options={'verbose_name_plural': 'Detroit 2020 Photos'},
        ),
        migrations.AlterModelOptions(
            name='la2021photos',
            options={'verbose_name_plural': 'LA 2021 Photos'},
        ),
    ]
