# Generated by Django 4.0.2 on 2022-05-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0010_denver2020photos_story_detroit2020photos_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denver2020photos',
            name='story',
        ),
        migrations.RemoveField(
            model_name='detroit2020photos',
            name='story',
        ),
        migrations.RemoveField(
            model_name='la2021photos',
            name='story',
        ),
    ]
