# Generated by Django 4.0.2 on 2022-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0011_remove_denver2020photos_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trip Stories',
            },
        ),
    ]
