# Generated by Django 4.0 on 2022-03-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(),
        ),
    ]
