# Generated by Django 4.0.2 on 2022-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0007_detroitphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detroit2020Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Detroit Photos',
            },
        ),
        migrations.CreateModel(
            name='LA2021Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'LA Photos',
            },
        ),
        migrations.RenameModel(
            old_name='DetroitPhotos',
            new_name='Denver2020Photos',
        ),
        migrations.AlterModelOptions(
            name='denver2020photos',
            options={'verbose_name_plural': 'Denver Photos'},
        ),
    ]
