# Generated by Django 4.0.2 on 2022-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0009_alter_denver2020photos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denver2020photos',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detroit2020photos',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='la2021photos',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
