# Generated by Django 4.0.2 on 2022-05-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkemorgn', '0012_tripstory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripStory',
        ),
    ]
